name: Reusable Python CI Pipeline

on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string

      main_module:
        required: true
        type: string

      python_versions:
        required: false
        default: '["3.11"]'
        type: string

      test_path:
        required: false
        default: tests
        type: string

      deploy:
        required: false
        default: false
        type: boolean

      run_lint:
        required: false
        type: boolean
        default: true

      run_security:
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  actions: read

jobs:
  ci:
    name: CI (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJson(inputs.python_versions) }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      # Checkout the CI framework repo (where scripts live)
      - name: Checkout framework
        uses: actions/checkout@v4
        with:
          repository: mohdshariq0092-droid/python-ci-framework
          ref: v1   # framework version
          path: ci-framework  # checkout under this folder

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-          

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build pytest pytest-cov wheel setuptools flake8 pylint bandit
#          pip install -e .

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Install wheel
        run: pip install dist/*.whl

      - name: Framework build step
        run: |
          set -euo pipefail
          bash ci-framework/scripts/build.sh ${{ inputs.project_type }}

      # Run unit tests + coverage
      - name: Run unit tests + coverage
        run: |
          pytest \
            -m "sanity" \
            --cov=${{ inputs.main_module }} \
            --cov-report=term-missing \
            --cov-report=xml \
            --junitxml=reports/tests.xml \
            ${{ inputs.test_path }}

      - name: Sanity tests
        run: bash ci-framework/scripts/sanity.sh

      # Run linting
      - name: Lint (flake8)
        if: ${{ inputs.run_lint }}
        working-directory: ${{ github.workspace }}
        run: flake8 -v .

      # Run pylint
      - name: Static analysis (pylint)
        if: ${{ inputs.run_lint }}
        working-directory: ${{ github.workspace }}
        run: pylint ${{ inputs.main_module }} --fail-under=8.0

      # Run security scan (Bandit)
      - name: Security scan
        if: ${{ inputs.run_security }}
        working-directory: ${{ github.workspace }}
        run: bandit -r ${{ inputs.main_module }}

      - name: Package
        run: |
          set -euo pipefail
          bash ci-framework/scripts/package.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist-${{ matrix.python-version }}
          path: |
            dist/
            reports/          

      - name: Deploy
        if: ${{ inputs.deploy }}
        run: |
          set -euo pipefail
          bash ci-framework/scripts/deploy.sh
